export {default as Home} from "./home";
export {default as Login} from "./login";
export {default as Profile} from "./profile";
export {default as Navbar} from "./header/navbar";
export {default as HeaderTop} from "./header/header-top";
export {default as Footer} from "./footer";
export {default as Catalog} from "./catalog"
export {default as AboutUs} from './about-us'
export {default as Contact} from "./contact"